language: go

go:
  - 1.14

sudo: required

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0

script:
  - golangci-lint run
  - bash ./acceptance.sh
  - go test -v ./... -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
