language: go

go:
  - 1.14

sudo: required

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0

script:
  - golangci-lint run
  - go test -v ./...
